import { useEffect, useState } from "react";
import Head from "next/head";
import BasicLayout from "../components/Layout";
import { Iwc } from "../containers/Iwc";
import { fetchIwcProductsDataApi, fetchScriptTagApi } from "./api/iwcTopGunApi";

export async function getServerSideProps() {
  const productData = await fetchIwcProductsDataApi().then((res) => {
    return res;
  });
  const scripts = await fetchScriptTagApi().then((script) => {
    return script;
  });
  return {
    props: {
      productData,
      scripts,
    },
  };
}

export default function Home(props) {
  const [loader, setLoader] = useState(false);
  const [data, setData] = useState<Record<string, any>>({});
  const [script, setScript] = useState({});

  const handleBodyScroll = () => {
    if (loader) {
      document.querySelector("body").style.overflow = "hidden";
    } else document.querySelector("body").style.overflow = "auto";
  };

  const fetchScriptTag = (data) => {
    if (data?.headscript) {
      document.head.innerHTML = document.head.innerHTML + data?.headscript;
    }
  };

  const fetchData = () => {
    const response = props?.productData;
    const scriptTags = props?.scripts;
    if (response?.data?.iwcCfWwWatchOverviewList !== undefined) {
      setData(response?.data?.iwcCfWwWatchOverviewList.items[0]);
      setLoader(false);
    }
    if (scriptTags?.data?.scriptTagList !== undefined) {
      setScript(scriptTags?.data?.scriptTagList.items[0]);
    }
  };

  useEffect(() => {
    setLoader(true);
    fetchData();
  }, []);

  useEffect(() => {
    handleBodyScroll();
    if (script) fetchScriptTag(script);
  }, [loader, script]);

  return (
    <BasicLayout>
      <Head>
        <title>Jet Black | IWC Schaffhausen</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon-96x96.png'
        />
        <meta name='keywords' />
        <meta name='description' />
        <meta
          name='robots'
          content={data ? data.robots : "index"}
        />

        <meta
          property='og:title'
          content={data ? data.ogtitle : "Jet Black | IWC Schaffhausen"}
        />
        <meta property='og:description' />

        <meta
          property='og:url'
          content={
            data
              ? data.ogurl
              : "https://www.iwc.com/us/en/watches-and-wonders/jet-black.html"
          }
        />
      </Head>
      <main>
        <Iwc
          data={data}
          loader={loader}
        />
      </main>
    </BasicLayout>
  );
}
